/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/3crosses.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, OrthographicCamera } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { scene } = useGLTF("/3crosses.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-228, 219, 0]}>
          <mesh
            geometry={nodes.Shape_0.geometry}
            material={nodes.Shape_0.material}
            position={[23.83, -100.08, 0]}
          />
          <mesh
            geometry={nodes.Shape_1.geometry}
            material={nodes.Shape_1.material}
            position={[192.2, -100.08, 0.01]}
          />
          <mesh
            geometry={nodes.Shape_2.geometry}
            material={nodes.Shape_2.material}
            position={[107.8, -45.72, 0.02]}
          />
        </group>
        <directionalLight
          intensity={0.7}
          decay={2}
          rotation={[-0.506, 0.629, 0.756]}
          target={nodes.Directional_Light.target}
        >
          <primitive
            object={nodes.Directional_Light.target}
            position={[0, 0, -1]}
          />
        </directionalLight>
        <OrthographicCamera
          makeDefault={false}
          far={100000}
          near={0}
          position={[564.009, 348.735, -748.517]}
          rotation={[-2.706, 0.599, 2.885]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3crosses.glb");
